package domain_test

// Property-based unit tests for the TenantLink aggregate (step 01-02,
// inter-tenant-transfer). No pre-authored acceptance test targets this file
// in isolation — it is exercised end-to-end starting at step 01-04's HTTP
// wiring — so these PBT unit tests ARE this step's own RED/GREEN obligation
// (see roadmap step 01-02's implementation_notes).
//
// Property-based by default (pgregory.net/rapid), mirroring the existing
// domain PBT harness in domain_property_test.go.

import (
	"errors"
	"testing"

	"ledgerops/internal/domain"
	"pgregory.net/rapid"
)

func genTenantID(t *rapid.T, label string) string {
	return rapid.StringMatching(`tnt_[a-z0-9]{4,8}`).Draw(t, label)
}

func genLinkID(t *rapid.T, label string) string {
	return rapid.StringMatching(`lnk_[a-z0-9]{4,8}`).Draw(t, label)
}

// TestProperty_AuthorizeTenantPair_CanonicalizationCatchesReversedOrder
// covers (a): AuthorizeTenantPair(B, A) is refused as
// tenant_link_already_exists when AuthorizeTenantPair(A, B) already granted
// an active link for the same unordered pair — canonicalization must sort
// before ever comparing against the snapshot, so a caller cannot evade the
// refusal by reversing argument order (I11, brief.md § Inter-tenant
// transfer).
func TestProperty_AuthorizeTenantPair_CanonicalizationCatchesReversedOrder(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		tenantA := genTenantID(t, "tenantA")
		tenantB := genTenantID(t, "tenantB")
		if tenantA == tenantB {
			t.Skip("generator drew the same tenant twice -- not a pair")
		}

		firstLinkID := genLinkID(t, "firstLinkID")
		secondLinkID := genLinkID(t, "secondLinkID")

		knownTenants := map[string]bool{tenantA: true, tenantB: true}

		first, err := domain.AuthorizeTenantPair(firstLinkID, tenantA, tenantB, nil, knownTenants)
		if err != nil {
			t.Fatalf("first AuthorizeTenantPair unexpectedly refused: %v", err)
		}

		// Reversed argument order against the snapshot containing the first
		// link -- must collide on the same canonicalized slot.
		_, err = domain.AuthorizeTenantPair(secondLinkID, tenantB, tenantA, []domain.TenantLink{first}, knownTenants)

		var violation domain.Violation
		if !errors.As(err, &violation) || violation.Kind() != domain.TenantLinkAlreadyExists {
			t.Fatalf("expected tenant_link_already_exists for reversed-order pair, got %v", err)
		}
	})
}

// TestProperty_AuthorizeTenantPair_ComplementEquality covers (b) for
// AuthorizeTenantPair: the declared delta is exactly one new
// {link_id, tenant_a, tenant_b, status: active} triple — every other link
// already present in the snapshot is untouched (brief.md § Inter-tenant
// transfer, "Complement equality").
func TestProperty_AuthorizeTenantPair_ComplementEquality(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		bystanderCount := rapid.IntRange(0, 5).Draw(t, "bystanderCount")
		bystanders := make([]domain.TenantLink, 0, bystanderCount)
		knownTenants := map[string]bool{}

		for i := 0; i < bystanderCount; i++ {
			bTenantA := genTenantID(t, "bystanderA")
			bTenantB := genTenantID(t, "bystanderB")
			if bTenantA == bTenantB {
				t.Skip("generator drew the same tenant twice for a bystander pair")
			}
			bLinkID := genLinkID(t, "bystanderLinkID")
			knownTenants[bTenantA] = true
			knownTenants[bTenantB] = true

			bystander, err := domain.AuthorizeTenantPair(bLinkID, bTenantA, bTenantB, bystanders, knownTenants)
			if err != nil {
				t.Skip("generated bystander pair collided -- not the property under test")
			}
			bystanders = append(bystanders, bystander)
		}

		newTenantA := genTenantID(t, "newTenantA")
		newTenantB := genTenantID(t, "newTenantB")
		if newTenantA == newTenantB {
			t.Skip("generator drew the same tenant twice for the new pair")
		}
		newLinkID := genLinkID(t, "newLinkID")
		knownTenants[newTenantA] = true
		knownTenants[newTenantB] = true

		before := append([]domain.TenantLink(nil), bystanders...)

		newLink, err := domain.AuthorizeTenantPair(newLinkID, newTenantA, newTenantB, bystanders, knownTenants)
		if err != nil {
			t.Skip("generated new pair collided with a bystander -- not the property under test")
		}

		// Every bystander link is byte-identical after the call --
		// AuthorizeTenantPair mutates nothing it was handed, it only
		// returns a new value.
		if len(bystanders) != len(before) {
			t.Fatalf("bystander snapshot slice changed size: before=%d after=%d", len(before), len(bystanders))
		}
		for i := range before {
			if before[i] != bystanders[i] {
				t.Fatalf("bystander link at %d mutated: before=%+v after=%+v", i, before[i], bystanders[i])
			}
		}

		if newLink.LinkID() != newLinkID {
			t.Fatalf("LinkID() = %q, want %q", newLink.LinkID(), newLinkID)
		}
		if newLink.Status() != domain.TenantLinkActive {
			t.Fatalf("Status() = %q, want %q", newLink.Status(), domain.TenantLinkActive)
		}
	})
}

// TestProperty_RevokeTenantLink_ComplementEquality covers (b) for
// RevokeTenantLink: status transitions active -> revoked on exactly the
// named link_id; every other link in the snapshot is untouched.
func TestProperty_RevokeTenantLink_ComplementEquality(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		linkCount := rapid.IntRange(1, 5).Draw(t, "linkCount")
		links := make([]domain.TenantLink, 0, linkCount)
		knownTenants := map[string]bool{}

		for i := 0; i < linkCount; i++ {
			tenantA := genTenantID(t, "tenantA")
			tenantB := genTenantID(t, "tenantB")
			if tenantA == tenantB {
				t.Skip("generator drew the same tenant twice")
			}
			linkID := genLinkID(t, "linkID")
			knownTenants[tenantA] = true
			knownTenants[tenantB] = true

			link, err := domain.AuthorizeTenantPair(linkID, tenantA, tenantB, links, knownTenants)
			if err != nil {
				t.Skip("generated pair collided -- not the property under test")
			}
			links = append(links, link)
		}

		touchedIndex := rapid.IntRange(0, len(links)-1).Draw(t, "touchedIndex")
		touchedLinkID := links[touchedIndex].LinkID()

		revoked, err := domain.RevokeTenantLink(touchedLinkID, links)
		if err != nil {
			t.Fatalf("RevokeTenantLink refused a link present in the snapshot: %v", err)
		}

		if revoked.LinkID() != touchedLinkID {
			t.Fatalf("LinkID() = %q, want %q", revoked.LinkID(), touchedLinkID)
		}
		if revoked.Status() != domain.TenantLinkRevoked {
			t.Fatalf("Status() = %q, want %q", revoked.Status(), domain.TenantLinkRevoked)
		}

		for i, original := range links {
			if i == touchedIndex {
				continue
			}
			if original != links[i] {
				t.Fatalf("untouched link at %d mutated: before=%+v after=%+v", i, original, links[i])
			}
		}
	})
}

// TestProperty_AuthorizeTenantPair_RefusesUnknownTenant covers (c):
// AuthorizeTenantPair refuses tenant_not_found (existing member, reused)
// naming whichever side is absent from knownTenants -- checked before the
// tenant_link_already_exists gate.
func TestProperty_AuthorizeTenantPair_RefusesUnknownTenant(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		tenantA := genTenantID(t, "tenantA")
		tenantB := genTenantID(t, "tenantB")
		if tenantA == tenantB {
			t.Skip("generator drew the same tenant twice -- not a pair")
		}
		linkID := genLinkID(t, "linkID")

		missingSide := rapid.SampledFrom([]string{"a", "b"}).Draw(t, "missingSide")
		knownTenants := map[string]bool{}
		if missingSide == "a" {
			knownTenants[tenantB] = true
		} else {
			knownTenants[tenantA] = true
		}

		_, err := domain.AuthorizeTenantPair(linkID, tenantA, tenantB, nil, knownTenants)

		var violation domain.Violation
		if !errors.As(err, &violation) || violation.Kind() != domain.TenantNotFound {
			t.Fatalf("expected tenant_not_found when a named tenant is absent, got %v", err)
		}
	})
}

// TestProperty_AuthorizeTenantPair_RefusesDuplicateActivePair covers (d):
// a second AuthorizeTenantPair for the same canonicalized pair while the
// first is still active is refused tenant_link_already_exists.
func TestProperty_AuthorizeTenantPair_RefusesDuplicateActivePair(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		tenantA := genTenantID(t, "tenantA")
		tenantB := genTenantID(t, "tenantB")
		if tenantA == tenantB {
			t.Skip("generator drew the same tenant twice -- not a pair")
		}
		firstLinkID := genLinkID(t, "firstLinkID")
		secondLinkID := genLinkID(t, "secondLinkID")
		knownTenants := map[string]bool{tenantA: true, tenantB: true}

		first, err := domain.AuthorizeTenantPair(firstLinkID, tenantA, tenantB, nil, knownTenants)
		if err != nil {
			t.Fatalf("first AuthorizeTenantPair unexpectedly refused: %v", err)
		}

		_, err = domain.AuthorizeTenantPair(secondLinkID, tenantA, tenantB, []domain.TenantLink{first}, knownTenants)

		var violation domain.Violation
		if !errors.As(err, &violation) || violation.Kind() != domain.TenantLinkAlreadyExists {
			t.Fatalf("expected tenant_link_already_exists for a duplicate active pair, got %v", err)
		}
	})
}

// TestProperty_RevokeThenReauthorize_MintsDistinctLinkID covers (e):
// revoking a link and then re-authorizing the same pair succeeds with a
// new, distinct link_id -- revocation is not a mutable toggle back to
// active (slice-01's own AC).
func TestProperty_RevokeThenReauthorize_MintsDistinctLinkID(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		tenantA := genTenantID(t, "tenantA")
		tenantB := genTenantID(t, "tenantB")
		if tenantA == tenantB {
			t.Skip("generator drew the same tenant twice -- not a pair")
		}
		firstLinkID := genLinkID(t, "firstLinkID")
		secondLinkID := genLinkID(t, "secondLinkID")
		if firstLinkID == secondLinkID {
			t.Skip("generator drew the same link id twice")
		}
		knownTenants := map[string]bool{tenantA: true, tenantB: true}

		first, err := domain.AuthorizeTenantPair(firstLinkID, tenantA, tenantB, nil, knownTenants)
		if err != nil {
			t.Fatalf("first AuthorizeTenantPair unexpectedly refused: %v", err)
		}

		revoked, err := domain.RevokeTenantLink(first.LinkID(), []domain.TenantLink{first})
		if err != nil {
			t.Fatalf("RevokeTenantLink unexpectedly refused: %v", err)
		}
		if revoked.Status() != domain.TenantLinkRevoked {
			t.Fatalf("Status() = %q, want %q", revoked.Status(), domain.TenantLinkRevoked)
		}

		second, err := domain.AuthorizeTenantPair(secondLinkID, tenantA, tenantB, []domain.TenantLink{revoked}, knownTenants)
		if err != nil {
			t.Fatalf("re-authorize after revoke unexpectedly refused: %v", err)
		}
		if second.LinkID() == first.LinkID() {
			t.Fatalf("re-authorize minted the same link_id as the revoked link: %q", second.LinkID())
		}
		if second.Status() != domain.TenantLinkActive {
			t.Fatalf("Status() = %q, want %q", second.Status(), domain.TenantLinkActive)
		}
	})
}

// TestTenantLink_NoConstructorOmitsTenantIDs covers I11: "no domain path
// constructs a TenantLink without both tenant ids populated" -- every
// accessor round-trips exactly what AuthorizeTenantPair was given, both
// tenant ids included, canonicalized.
func TestTenantLink_NoConstructorOmitsTenantIDs(t *testing.T) {
	link, err := domain.AuthorizeTenantPair("lnk_1", "tnt_beacon", "tnt_acme", nil, map[string]bool{
		"tnt_acme":   true,
		"tnt_beacon": true,
	})
	if err != nil {
		t.Fatalf("AuthorizeTenantPair unexpected error: %v", err)
	}
	if link.LinkID() != "lnk_1" {
		t.Fatalf("LinkID() = %q, want %q", link.LinkID(), "lnk_1")
	}
	if link.TenantA() != "tnt_acme" || link.TenantB() != "tnt_beacon" {
		t.Fatalf("TenantA/TenantB = %q/%q, want canonicalized tnt_acme/tnt_beacon", link.TenantA(), link.TenantB())
	}
	if link.Status() != domain.TenantLinkActive {
		t.Fatalf("Status() = %q, want %q", link.Status(), domain.TenantLinkActive)
	}
}

// TestRevokeTenantLink_RefusesUnknownLinkID covers the RevokeTenantLink
// refusal path: naming a link_id absent from the snapshot returns
// tenant_link_not_found (existing member, reused from the RED scaffold in
// violation.go).
func TestRevokeTenantLink_RefusesUnknownLinkID(t *testing.T) {
	_, err := domain.RevokeTenantLink("lnk_ghost", nil)

	var violation domain.Violation
	if !errors.As(err, &violation) || violation.Kind() != domain.TenantLinkNotFound {
		t.Fatalf("expected tenant_link_not_found, got %v", err)
	}
}
